#! /bin/bash
echo "enter filename in which you want to read "
read fileName

if [[ -f  "$fileName" ]]
then
	while IFS=""  read -r line
	do
		echo "$line"
	done < $fileName
else
	echo "$fileName doesnt exist"
fi

